{% set name = "jekyll-sass-converter" %}
{% set version = "2.0.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: a229262039933d3f482dc4a73f4dce508e392566ead5cbd1abdfe38d6e116c39

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-sassc >=2.0.1,<3.0

test:
  commands:
    - gem list | grep -s {{ name }}
    # We can't test the module because it depends on jekyll itself
    # - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A basic Sass converter for Jekyll.

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/jekyll/{{ name }}

extra:
  recipe-maintainers:
    - sodre
