travis:
  secure:
    BINSTAR_TOKEN: fqGS2nbHOZwK1QNk6qtp34qRok6mC8oQg7n3PH5arrCseukwlXZKC/EtfRj+3bMFKHtBxW42QjryukabdstfDSfVo3NNeLS/bdS4DXPtT+VEjnWcumdf9ogJdGy1im2F8VizbO2ygjksOku3esSi6cUN0tF0IerShZbp5rLh8hAVc6v1xYb8AwjvBe87M6+VMgaJ7cxifWPdxNbnnHXgQrxq6ECQyIsiyIavwzk/I2MPzIhU73v575oWl+kZpN+FhAxN/oThHEJe0KbOeR6jugL+JQ30GNChxctFl+aNx9Syd5YqL4Z3sKMkgFksWYzy2fyQK1m5Z3dgo2lSlV3yK1SyCIlgesIvTWZ9Gb8d3l2/444kFnaRWznPWC1Rwcg4374XEbLNnWdsEZl2rpeiLW5HTht2Y8WSytUu1FsPRCAGnKNfIoQQ9iOzVSptmsBkew+1h44Hi8cBLsWOCxHpJk1iFXUuDPmxP6nBByKod6B2gikgYYW7sMRuUPaWmPDarWVxU5AoTS+ZdfXS53oDbvizfd3ze36ShF3dKWD3/OK6+HG7VKe9yzqo+MQT5DurtUhFC6hBiTrNAm8jhzS5YYIAsQxBZIho1G19gpWGEV98WNwjeow+aRPrlBmPhZNVaC5bfyFQYOyR/1FWFkGIh8IFgUReaQP7inRvDwi4jlE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
